### ISSUE TITLE
Написать аннотацию к студенческому семинару

### ISSUE THREAD

**Issue by PavelTesemnikov** [PavelTesemnikov/work_with_Bruce#2]

**Comment by bruceback** [comment]
### Разбор лекций курса «Введение в финансовую математику» от фонда «Институт «Вега»

Основным объектом нашего внимания станет биномиальная модель рынка с одним моментом времени, что позволит перенести главные идеи на многошаговый случай, а именно на модель Кокса-Росса-Рубинштейна. В этой модели выведем условие на отсутствие арбитража и формулу риск-нейтральных вероятностей, и установим связь между этими понятиями.

Участники семинара обретут понимание фундаментальных концепций рассматриваемой теории и научатся считать справедливые цены производных инструментов.

**Comment by bruceback** [comment]
@PavelTesemnikov

**Comment by PavelTesemnikov** [comment]
@brucebek, немного подкорректировал:

### Разбор лекций курса «Введение в финансовую математику» от фонда «Институт «Вега»

Основным объектом нашего внимания станет биномиальная модель рынка за одну единицу времени. Мы обсудим основные идеи на примере этой простой модели, а затем перенесём их на многошаговый случай, а именно, на модель Кокса - Росса - Рубинштейна. Для этой модели мы выведем условие на отсутствие арбитража и формулу для вычисления риск-нейтральных вероятностей, а также установим связь между этими понятиями.

Мы обсудим некоторые фундаментальные концепции рассматриваемой теории и научимся определять справедливые цены производных инструментов.
