### ISSUE TITLE
Разбор лекций на 13 марта

### ISSUE THREAD

**Issue by PavelTesemnikov** [PavelTesemnikov/work_with_Bruce#3]
На мини семинаре от 10 марта 2023 хотелось бы:

- [x] **Закончить обсуждение кумулянтов.** Хотелось бы обсудить теорему 2.3, упражнение 2.4. (2-3 стр)
- [x] **Обсудить важные семейства распределений.** Тут хочется упомянуть о модели Блэка - Шоулза. (3-4 стр)
- [x] **Обсудить ЦПТ**. Хотелось бы обсудить упражнение 2.7. (4 стр)
- [ ] **Обсудить безгранично делимые распределения.** Обязательно нужно хорошенько разобраться в определениях и всех примерах. Попробовать проверить теорему Леви - Хинчина для всех примеров. Обязательно нужно поговорить об устойчивых распределениях и обсудить упражнения 2.14-2.20. (5-7 стр)

**Доказательство теоремы Леви - Хинчина предлагаю пока не трогать**.

**Comment by bruceback** [comment]
Я так понимаю, что в упражнении 2.4. рассматривают не произвольное распределение Бернулли, а с параметром $p=\frac{1}{2}$?

По неравенству Йенсена доказываем, что наименьшее значение Куртозиса это $-2$, тогда выводим условие на p:

$$\frac{\mathbb{E}(\xi - \mathbb{E})^4}{(\mathbb{D}\xi)^2}=\frac{p^2-p+1}{p(1-p)}=1 \iff 2p^2 - 2p + 1 = 0 \iff p = \frac{1}{2}$$

**Comment by PavelTesemnikov** [comment]
**Представление Леви &ndash; Хинчина для распределения Пуассона с параметром $\lambda$**

Пусть с.в.  $X$ имеет распределение Пуассона с параметром $\lambda$. Характеристическая функция
$$\phi_{X}(t) = \mathbf{E}e^{itX}=\sum_{k=0}^{\infty}e^{itk}\frac{\lambda^{k}}{k!}e^{-\lambda}=\exp(\lambda(e^{it}-1)).$$

Нам нужно представить логарифм этой функции в виде $$L(t) = ibt + \int_{\mathbb{R}} \left[ e^{itx} - 1 - \frac{itx}{1+x^2} \right] \frac{1 + x^2}{x^2} \mu(dx) $$ выбором $\mu$ и $b$. Заметим, что первые два слагаемых в квадратных скобках уже дают почти то, что нужно, если положить $x = 1$. Поэтому, разумно рассмотреть меру $\mu$, вырожденную в точке $1$, т.е. $\mu(B) = c$, если $1 \in B$ и $\mu(B)=0$ иначе. Константа $c$ подлежит определению.

Такая мера $\mu$ превращает $L(t)$ в $$L(t) = ibt + \left[ e^{it} - 1 - \frac{it}{2} \right] \cdot 2 \cdot c = 2c(e^{it}-1) + (b-c) it.$$

При $c = b = \lambda/2$ получаем, что $$L(t) = \lambda (e^{it}-1) = \log \phi_{X}(t).$$

@brucebek

**Comment by PavelTesemnikov** [comment]
> Я так понимаю, что в упражнении 2.4. рассматривают не произвольное распределение Бернулли, а с параметром p=12?
> 
> По неравенству Йенсена доказываем, что наименьшее значение Куртозиса это −2, тогда выводим условие на p:

Похоже на правду. Только мне кажется, что там арифметическая ошибка: $$\frac{\mathbf{E}(\xi-\mathbf{E}\xi)^4}{(\mathbf{D}\xi)^2}=\frac{3p^2-3p+1}{p(1-p)}=1 \iff 4p^2 - 4p +1 = (2p-1)^2=0 \iff p=1/2.$$

**Comment by PavelTesemnikov** [comment]
Формула для кумулянтов $$c_{n}=\sum_{k=1}^{n}\frac{(-1)^{k-1}}{k} \sum_{i_1 + \ldots + i_k = n} {n\choose {i_1,i_2,\ldots,i_k}} m_{i_1} m_{i_2} \ldots m_{i_k},$$
где индексы $i_1, i_2, \ldots, i_{k} \ge 1$.
